@ECHO OFF

SETLOCAL ENABLEDELAYEDEXPANSION

where /q git

IF ERRORLEVEL 1 (
    ECHO Please install git in your PATH to generate version info.
    EXIT /B 1
) ELSE (
    FOR /F "delims=" %%i IN ('git describe --tags') DO (
        SET VERSION=%%i
        ECHO /* This file is automatically generated on build! */ > src/keynavish/versioninfo.d
        ECHO[ >> src/keynavish/versioninfo.d
        ECHO module keynavish.versioninfo; >> src/keynavish/versioninfo.d
        ECHO[ >> src/keynavish/versioninfo.d
        ECHO enum gitVersion = "!VERSION!"; >> src/keynavish/versioninfo.d
        ECHO Version info written to 'src/keynavish/versioninfo.d'.
    )
)

ENDLOCAL