@ECHO OFF

REM
REM This file is a bit of a mess, suggestions for alternatives would be
REM much appreciated.
REM

SETLOCAL ENABLEDELAYEDEXPANSION

WHERE /q git

IF ERRORLEVEL 1 (
    ECHO Please install git in your PATH to generate version info.
    EXIT /B 1
) ELSE (
    FOR /F "delims=" %%i IN ('git describe --tags') DO (
        SET VERSION=%%i
        FOR /F "tokens=1,2,3,4 delims=.-" %%a IN ("!VERSION:v=!.0") DO SET WINVERSION=%%a,%%b,%%c,%%d

        ECHO /* This file is automatically generated on build! */ > src/keynavish/versioninfo.d
        ECHO[ >> src/keynavish/versioninfo.d
        ECHO module keynavish.versioninfo; >> src/keynavish/versioninfo.d
        ECHO[ >> src/keynavish/versioninfo.d
        ECHO enum gitVersion = "!VERSION!"; >> src/keynavish/versioninfo.d

        ECHO 1 VERSIONINFO ^

        FILEVERSION !WINVERSION! ^

        PRODUCTVERSION !WINVERSION! ^

        FILEOS 0x40004 ^

        FILETYPE 0x1 ^

        { ^

        BLOCK "StringFileInfo" ^

        { ^

        	BLOCK "040904B0" ^

        	{ ^

        		VALUE "FileDescription", "keynavish – Control the mouse with the keyboard, on Windows" ^

        		VALUE "InternalName", "keynavish.exe" ^

        		VALUE "OriginalFilename", "keynavish.exe" ^

        		VALUE "CompanyName", "Les De Ridder" ^

        		VALUE "LegalCopyright", "© 2021, Les De Ridder <les@lesderid.net>" ^

        		VALUE "ProductName", "keynavish" ^

        		VALUE "FileVersion", "!VERSION:v=!" ^

        		VALUE "ProductVersion", "!VERSION:v=!" ^

        	} ^

        } ^

         ^

        BLOCK "VarFileInfo" ^

        { ^

        	VALUE "Translation", 0x0409 0x04B0 ^

        } ^

        } > src/keynavish/versioninfo.rc

        ECHO Version info written to 'src/keynavish/versioninfo.{d,rc}'.
        .\tools\llvm-rc.exe /C 65001 src\keynavish\versioninfo.rc
        ECHO Converted 'src/keynavish/versioninfo.rc' to 'src/keynavish/versioninfo.res'.
    )
)

ENDLOCAL
