#!/bin/sh
#
# Generates src/keynavish/versioninfo.d from the current git tag.
#
# The Windows build additionally generates a VERSIONINFO .rc/.res resource
# (see generate-version-info.bat); on macOS the equivalent metadata lives in
# the bundle's Info.plist instead, written by tools/make-bundle.sh.
#
set -eu

SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
ROOT=$(dirname "$SCRIPT_DIR")
OUT="$ROOT/src/keynavish/versioninfo.d"

if ! command -v git >/dev/null 2>&1; then
	echo "Please install git in your PATH to generate version info." >&2
	exit 1
fi

VERSION=$(cd "$ROOT" && git describe --tags 2>/dev/null || echo "unknown")

cat > "$OUT" <<EOF
/* This file is automatically generated on build! */

module keynavish.versioninfo;

enum gitVersion = "$VERSION";
EOF

echo "Version info written to 'src/keynavish/versioninfo.d' ($VERSION)."
